### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kaaetech** [hunterbdm/AdidasQueuer#1]
Enter country code: DK
Traceback (most recent call last):
  File "AdidasQueuer.py", line 205, in <module>
    main()
  File "AdidasQueuer.py", line 78, in main
    country_code = input('Enter country code: ').upper()
  File "<string>", line 1, in <module>
NameError: name 'DK' is not defined
Emils-MacBook-Air:AdidasQueuer emilkudahl$

**Comment by kaaetech** [comment]
nvm closing. python3 was solution
